### ISSUE TITLE
Access Token Expiration

### ISSUE THREAD

**Issue by sicktastic** [koshilife/omniauth-zoom#14]
I am using this with `omniauth` and `devise`.

The initial access token from authorization only lasts for 1 hour, does this gem handle [refreshing the access token](https://marketplace.zoom.us/docs/guides/auth/oauth#refreshing) that lasts for 15 years?

I am using this so our users can create their own zoom meetings from our Rails app, but I was wondering if we have to manually refresh the token after the initial Oauth authorization.

**Comment by koshilife** [comment]
Hi @antwonlee,

The access token management is out of scope in this library.
When an access token expires you need to get new one using a refresh token manually like below.

```ruby
require 'faraday'

CLIENT_ID = '<YOUR_CLIENT_ID>'
CLIENT_SECRET = '<YOUR_CLIENT_SECRET>'
REFRESH_TOKEN = '<YOUR_REFRESH_TOKEN>'

headers_secret = Base64.strict_encode64("#{CLIENT_ID}:#{CLIENT_SECRET}")
headers = { 'Authorization': "Basic #{headers_secret}" }

params = { grant_type: 'refresh_token', refresh_token: REFRESH_TOKEN}
url = "https://zoom.us/oauth/token?#{params.to_query}"
res = Faraday.post url do |req|
  req.headers = headers
end
raise 'zoom api error' unless res.status == 200

body = JSON.parse(res.body, symbolize_names: true)
new_access_token = body[:access_token]
new_refresh_token = body[:refresh_token]
access_token_expires_at = Time.current.since(body[:expires_in])
```

**Comment by sicktastic** [comment]
@koshilife that's what I thought.  Thanks for replying so quickly.  Great job creating this handy gem as well, it has been a big help!!
