### ISSUE TITLE
I am unable to use /auth/zoom 

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [koshilife/omniauth-zoom#22]
ruby '2.6.6'
'rails', '~> 5.2.6'

```
Rails.application.config.middleware.use OmniAuth::Builder do
    zoom_scopes = %i[user_profile meeting:write]
    zoom_client_id = '12'
    zoom_client_secret = '123'
    provider :zoom, zoom_client_id, zoom_client_secret, :scope => zoom_scopes.join(',')
  end
  ```
  Getting error of
  No route matches [GET] "/auth/zoom"

**Comment by koshilife** [comment]
Hi @ayazahmadtarar-pikessoft,

Thank you for reaching out.
Could you share a result of `$ rails routes` or `$ rails routes | grep zoom`?

**Comment by ayazahmadtarar-pikessoft** [comment]
<img width="1245" alt="Screenshot 2021-12-03 at 7 28 07 PM" src="https://user-images.githubusercontent.com/23359792/144618964-801b0f25-27af-47cf-bf1e-ca6e57853172.png">

**Comment by ayazahmadtarar-pikessoft** [comment]
The problem is that zoom auth send get request after addin `OmniAuth.config.allowed_request_methods = [:post, :get]` in omniauth.rb it worked and updating callback route to get

**Comment by koshilife** [comment]
@ayazahmadtarar-pikessoft

Thank goodness for that.
It seems to be a behavior since OmniAuth 2.0 series.
I hope the following links help you to understand more.

https://github.com/omniauth/omniauth/releases/tag/v2.0.0
https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0
